var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(auth)/login/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__a6ed5feb._.js")
R.c("server/chunks/ssr/_a30adabf._.js")
R.c("server/chunks/ssr/_ea9828b6._.js")
R.c("server/chunks/ssr/[root-of-the-server]__a80f0e21._.js")
R.c("server/chunks/ssr/node_modules__pnpm_6dbffa4f._.js")
R.c("server/chunks/ssr/9d1c8_next_dist_2494b150._.js")
R.c("server/chunks/ssr/src_app_5b2047f8._.js")
R.c("server/chunks/ssr/src_app_global-error_tsx_aa661ba4._.js")
R.c("server/chunks/ssr/[root-of-the-server]__dd0ab9da._.js")
R.c("server/chunks/ssr/9d1c8_next_dist_client_components_51b6c503._.js")
R.c("server/chunks/ssr/9d1c8_next_dist_client_components_builtin_forbidden_3b5062d3.js")
R.c("server/chunks/ssr/9d1c8_next_dist_client_components_builtin_unauthorized_b8f142a3.js")
R.c("server/chunks/ssr/src_app_(auth)_layout_tsx_92f1b6d4._.js")
R.c("server/chunks/ssr/_next-internal_server_app_(auth)_login_page_actions_bf14911e.js")
R.m(64905)
module.exports=R.m(64905).exports
