#!/bin/sh
# summa.sh — One-liner installer for Summa
# Usage: curl -sSL https://get.summa.sh | sh
#
# This script:
#   1. Checks that Docker (and Docker Compose) are installed
#   2. Creates ~/summa as the install directory
#   3. Writes a docker-compose.yml and .env with secure defaults
#   4. Pulls the Docker image and starts Summa

set -e

INSTALL_DIR="${SUMMA_DIR:-$HOME/summa}"
IMAGE="ghcr.io/summa-app/summa:latest"

# ─── Colors ────────────────────────────────────────────────────────────────────
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

info()    { printf "${GREEN}[summa]${NC} %s\n" "$1"; }
warn()    { printf "${YELLOW}[summa]${NC} %s\n" "$1"; }
error()   { printf "${RED}[summa] ERROR:${NC} %s\n" "$1" >&2; exit 1; }

# ─── Dependency checks ─────────────────────────────────────────────────────────
check_deps() {
    if ! command -v docker >/dev/null 2>&1; then
        error "Docker is not installed. Install it from https://docs.docker.com/get-docker/ and re-run."
    fi

    if ! docker compose version >/dev/null 2>&1; then
        error "Docker Compose (v2) is not available. Ensure your Docker installation includes the 'compose' plugin."
    fi

    if ! docker info >/dev/null 2>&1; then
        error "Docker daemon is not running. Start Docker and re-run."
    fi
}

# ─── Secret generation ─────────────────────────────────────────────────────────
generate_secret() {
    if command -v openssl >/dev/null 2>&1; then
        openssl rand -hex 32
    elif [ -r /dev/urandom ]; then
        dd if=/dev/urandom bs=32 count=1 2>/dev/null | od -An -tx1 | tr -d ' \n'
    else
        error "Cannot generate a random secret. Please set BETTER_AUTH_SECRET manually in $INSTALL_DIR/.env"
    fi
}

# ─── Main install ──────────────────────────────────────────────────────────────
main() {
    info "Starting Summa installer..."
    info "Install directory: $INSTALL_DIR"

    # 1. Check dependencies
    check_deps

    # 2. Create install directory
    if [ -d "$INSTALL_DIR" ]; then
        warn "Directory $INSTALL_DIR already exists. Continuing (existing .env will not be overwritten)."
    else
        mkdir -p "$INSTALL_DIR"
        info "Created $INSTALL_DIR"
    fi

    cd "$INSTALL_DIR"

    # 3. Write docker-compose.yml
    cat > docker-compose.yml << 'COMPOSE'
services:
  app:
    image: ghcr.io/summa-app/summa:latest
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://summa:${POSTGRES_PASSWORD}@db:5432/summa
      BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET}
      BETTER_AUTH_URL: ${BETTER_AUTH_URL:-http://localhost:3000}
      PLAID_CLIENT_ID: ${PLAID_CLIENT_ID:-}
      PLAID_SECRET: ${PLAID_SECRET:-}
      PLAID_ENV: ${PLAID_ENV:-sandbox}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY:-}
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: summa
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: summa
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U summa"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  pgdata:
COMPOSE
    info "Wrote docker-compose.yml"

    # 4. Write .env (only if it doesn't already exist)
    if [ ! -f .env ]; then
        info "Generating secrets..."
        AUTH_SECRET="$(generate_secret)"
        DB_PASS="$(generate_secret | head -c 24)"

        cat > .env << ENV
# Summa configuration
# Generated by summa.sh on $(date -u '+%Y-%m-%dT%H:%M:%SZ')

# Database password (auto-generated)
POSTGRES_PASSWORD=${DB_PASS}

# Session signing secret — keep this private
BETTER_AUTH_SECRET=${AUTH_SECRET}

# Public URL of your Summa instance (change if not running on localhost)
BETTER_AUTH_URL=http://localhost:3000

# ── Optional: Plaid bank connections ──────────────────────────────────────────
# PLAID_CLIENT_ID=
# PLAID_SECRET=
# PLAID_ENV=sandbox

# ── Optional: Plaid token encryption (32-byte hex) ────────────────────────────
# ENCRYPTION_KEY=
ENV
        info "Wrote .env with generated secrets"
    else
        warn ".env already exists — skipping to avoid overwriting existing config"
    fi

    # 5. Pull image
    info "Pulling $IMAGE ..."
    docker pull "$IMAGE"

    # 6. Start
    info "Starting Summa..."
    docker compose up -d

    printf "\n"
    info "────────────────────────────────────────────────────"
    info "  Summa is running at http://localhost:3000"
    info "  Install directory: $INSTALL_DIR"
    info ""
    info "  Useful commands:"
    info "    docker compose -f $INSTALL_DIR/docker-compose.yml logs -f"
    info "    docker compose -f $INSTALL_DIR/docker-compose.yml down"
    info "    docker compose -f $INSTALL_DIR/docker-compose.yml pull && docker compose -f $INSTALL_DIR/docker-compose.yml up -d"
    info "────────────────────────────────────────────────────"
}

main "$@"
