// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/dashboard" | "/import/kubera" | "/login" | "/portfolio/[portfolioId]" | "/portfolio/[portfolioId]/asset/[assetId]" | "/register" | "/settings" | "/settings/connections"
type AppRouteHandlerRoutes = "/api/assets/[id]" | "/api/assets/[id]/move" | "/api/assets/[id]/refresh" | "/api/assets/[id]/snapshots" | "/api/assets/[id]/transactions" | "/api/auth/[...all]" | "/api/auth/check-user" | "/api/connections" | "/api/connections/sync" | "/api/connections/wallet/[id]/sync" | "/api/exchange-rates" | "/api/health" | "/api/import/kubera" | "/api/plaid/connections" | "/api/plaid/connections/[id]" | "/api/plaid/connections/[id]/accounts" | "/api/plaid/connections/[id]/sync" | "/api/plaid/exchange-token" | "/api/plaid/fix-misplaced-liabilities" | "/api/plaid/link-token" | "/api/plaid/status" | "/api/plaid/webhook" | "/api/portfolios" | "/api/portfolios/[id]" | "/api/portfolios/[id]/assets" | "/api/portfolios/[id]/assets/reorder" | "/api/portfolios/[id]/export-csv" | "/api/portfolios/[id]/import-csv" | "/api/portfolios/[id]/import-csv/confirm" | "/api/portfolios/[id]/sections" | "/api/portfolios/[id]/sections/reorder" | "/api/portfolios/[id]/sheets" | "/api/portfolios/[id]/sheets/reorder" | "/api/portfolios/[id]/snapshots" | "/api/portfolios/[id]/sync" | "/api/portfolios/onboard" | "/api/prices/quote" | "/api/prices/search" | "/api/simplefin/connections" | "/api/simplefin/connections/[id]" | "/api/simplefin/connections/[id]/accounts" | "/api/simplefin/connections/[id]/sync" | "/api/snapshots/take"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/assets/[id]": { "id": string; }
  "/api/assets/[id]/move": { "id": string; }
  "/api/assets/[id]/refresh": { "id": string; }
  "/api/assets/[id]/snapshots": { "id": string; }
  "/api/assets/[id]/transactions": { "id": string; }
  "/api/auth/[...all]": { "all": string[]; }
  "/api/auth/check-user": {}
  "/api/connections": {}
  "/api/connections/sync": {}
  "/api/connections/wallet/[id]/sync": { "id": string; }
  "/api/exchange-rates": {}
  "/api/health": {}
  "/api/import/kubera": {}
  "/api/plaid/connections": {}
  "/api/plaid/connections/[id]": { "id": string; }
  "/api/plaid/connections/[id]/accounts": { "id": string; }
  "/api/plaid/connections/[id]/sync": { "id": string; }
  "/api/plaid/exchange-token": {}
  "/api/plaid/fix-misplaced-liabilities": {}
  "/api/plaid/link-token": {}
  "/api/plaid/status": {}
  "/api/plaid/webhook": {}
  "/api/portfolios": {}
  "/api/portfolios/[id]": { "id": string; }
  "/api/portfolios/[id]/assets": { "id": string; }
  "/api/portfolios/[id]/assets/reorder": { "id": string; }
  "/api/portfolios/[id]/export-csv": { "id": string; }
  "/api/portfolios/[id]/import-csv": { "id": string; }
  "/api/portfolios/[id]/import-csv/confirm": { "id": string; }
  "/api/portfolios/[id]/sections": { "id": string; }
  "/api/portfolios/[id]/sections/reorder": { "id": string; }
  "/api/portfolios/[id]/sheets": { "id": string; }
  "/api/portfolios/[id]/sheets/reorder": { "id": string; }
  "/api/portfolios/[id]/snapshots": { "id": string; }
  "/api/portfolios/[id]/sync": { "id": string; }
  "/api/portfolios/onboard": {}
  "/api/prices/quote": {}
  "/api/prices/search": {}
  "/api/simplefin/connections": {}
  "/api/simplefin/connections/[id]": { "id": string; }
  "/api/simplefin/connections/[id]/accounts": { "id": string; }
  "/api/simplefin/connections/[id]/sync": { "id": string; }
  "/api/snapshots/take": {}
  "/dashboard": {}
  "/import/kubera": {}
  "/login": {}
  "/portfolio/[portfolioId]": { "portfolioId": string; }
  "/portfolio/[portfolioId]/asset/[assetId]": { "portfolioId": string; "assetId": string; }
  "/register": {}
  "/settings": {}
  "/settings/connections": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
