// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/(app)/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/import/kubera/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/import/kubera">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/import/kubera/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/portfolio/[portfolioId]/asset/[assetId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/portfolio/[portfolioId]/asset/[assetId]">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/portfolio/[portfolioId]/asset/[assetId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/portfolio/[portfolioId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/portfolio/[portfolioId]">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/portfolio/[portfolioId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/settings/connections/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/connections">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/settings/connections/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(auth)/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(auth)/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/register">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/assets/[id]/move/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/assets/[id]/move">> = Specific
  const handler = {} as typeof import("../../src/app/api/assets/[id]/move/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/assets/[id]/refresh/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/assets/[id]/refresh">> = Specific
  const handler = {} as typeof import("../../src/app/api/assets/[id]/refresh/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/assets/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/assets/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/assets/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/assets/[id]/snapshots/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/assets/[id]/snapshots">> = Specific
  const handler = {} as typeof import("../../src/app/api/assets/[id]/snapshots/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/assets/[id]/transactions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/assets/[id]/transactions">> = Specific
  const handler = {} as typeof import("../../src/app/api/assets/[id]/transactions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/[...all]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/[...all]">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/[...all]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/check-user/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/check-user">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/check-user/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/connections/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/connections">> = Specific
  const handler = {} as typeof import("../../src/app/api/connections/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/connections/sync/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/connections/sync">> = Specific
  const handler = {} as typeof import("../../src/app/api/connections/sync/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/connections/wallet/[id]/sync/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/connections/wallet/[id]/sync">> = Specific
  const handler = {} as typeof import("../../src/app/api/connections/wallet/[id]/sync/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/exchange-rates/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/exchange-rates">> = Specific
  const handler = {} as typeof import("../../src/app/api/exchange-rates/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health">> = Specific
  const handler = {} as typeof import("../../src/app/api/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/import/kubera/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/import/kubera">> = Specific
  const handler = {} as typeof import("../../src/app/api/import/kubera/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/plaid/connections/[id]/accounts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/plaid/connections/[id]/accounts">> = Specific
  const handler = {} as typeof import("../../src/app/api/plaid/connections/[id]/accounts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/plaid/connections/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/plaid/connections/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/plaid/connections/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/plaid/connections/[id]/sync/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/plaid/connections/[id]/sync">> = Specific
  const handler = {} as typeof import("../../src/app/api/plaid/connections/[id]/sync/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/plaid/connections/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/plaid/connections">> = Specific
  const handler = {} as typeof import("../../src/app/api/plaid/connections/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/plaid/exchange-token/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/plaid/exchange-token">> = Specific
  const handler = {} as typeof import("../../src/app/api/plaid/exchange-token/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/plaid/fix-misplaced-liabilities/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/plaid/fix-misplaced-liabilities">> = Specific
  const handler = {} as typeof import("../../src/app/api/plaid/fix-misplaced-liabilities/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/plaid/link-token/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/plaid/link-token">> = Specific
  const handler = {} as typeof import("../../src/app/api/plaid/link-token/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/plaid/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/plaid/status">> = Specific
  const handler = {} as typeof import("../../src/app/api/plaid/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/plaid/webhook/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/plaid/webhook">> = Specific
  const handler = {} as typeof import("../../src/app/api/plaid/webhook/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/portfolios/[id]/assets/reorder/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/portfolios/[id]/assets/reorder">> = Specific
  const handler = {} as typeof import("../../src/app/api/portfolios/[id]/assets/reorder/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/portfolios/[id]/assets/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/portfolios/[id]/assets">> = Specific
  const handler = {} as typeof import("../../src/app/api/portfolios/[id]/assets/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/portfolios/[id]/export-csv/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/portfolios/[id]/export-csv">> = Specific
  const handler = {} as typeof import("../../src/app/api/portfolios/[id]/export-csv/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/portfolios/[id]/import-csv/confirm/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/portfolios/[id]/import-csv/confirm">> = Specific
  const handler = {} as typeof import("../../src/app/api/portfolios/[id]/import-csv/confirm/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/portfolios/[id]/import-csv/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/portfolios/[id]/import-csv">> = Specific
  const handler = {} as typeof import("../../src/app/api/portfolios/[id]/import-csv/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/portfolios/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/portfolios/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/portfolios/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/portfolios/[id]/sections/reorder/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/portfolios/[id]/sections/reorder">> = Specific
  const handler = {} as typeof import("../../src/app/api/portfolios/[id]/sections/reorder/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/portfolios/[id]/sections/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/portfolios/[id]/sections">> = Specific
  const handler = {} as typeof import("../../src/app/api/portfolios/[id]/sections/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/portfolios/[id]/sheets/reorder/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/portfolios/[id]/sheets/reorder">> = Specific
  const handler = {} as typeof import("../../src/app/api/portfolios/[id]/sheets/reorder/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/portfolios/[id]/sheets/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/portfolios/[id]/sheets">> = Specific
  const handler = {} as typeof import("../../src/app/api/portfolios/[id]/sheets/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/portfolios/[id]/snapshots/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/portfolios/[id]/snapshots">> = Specific
  const handler = {} as typeof import("../../src/app/api/portfolios/[id]/snapshots/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/portfolios/[id]/sync/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/portfolios/[id]/sync">> = Specific
  const handler = {} as typeof import("../../src/app/api/portfolios/[id]/sync/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/portfolios/onboard/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/portfolios/onboard">> = Specific
  const handler = {} as typeof import("../../src/app/api/portfolios/onboard/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/portfolios/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/portfolios">> = Specific
  const handler = {} as typeof import("../../src/app/api/portfolios/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/prices/quote/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/prices/quote">> = Specific
  const handler = {} as typeof import("../../src/app/api/prices/quote/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/prices/search/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/prices/search">> = Specific
  const handler = {} as typeof import("../../src/app/api/prices/search/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/simplefin/connections/[id]/accounts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/simplefin/connections/[id]/accounts">> = Specific
  const handler = {} as typeof import("../../src/app/api/simplefin/connections/[id]/accounts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/simplefin/connections/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/simplefin/connections/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/simplefin/connections/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/simplefin/connections/[id]/sync/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/simplefin/connections/[id]/sync">> = Specific
  const handler = {} as typeof import("../../src/app/api/simplefin/connections/[id]/sync/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/simplefin/connections/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/simplefin/connections">> = Specific
  const handler = {} as typeof import("../../src/app/api/simplefin/connections/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/snapshots/take/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/snapshots/take">> = Specific
  const handler = {} as typeof import("../../src/app/api/snapshots/take/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/(app)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(auth)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
